import { PrismaClient, UserRole } from '@prisma/client';
import bcrypt from 'bcryptjs';
import { encryptApiKeySecret, hashApiKeySecret } from '../lib/companyApiKeys';

const prisma = new PrismaClient();
const hardcodedProviderApiKey = 'ck_live_provider1_hacknarok2026';

function addMinutes(date: Date, minutes: number) {
  return new Date(date.getTime() + minutes * 60 * 1000);
}

async function createUser(
  email: string,
  firstName: string,
  lastName: string,
  plainPassword: string,
  role: UserRole,
) {
  const hashed = await bcrypt.hash(plainPassword, 10);
  const user = await prisma.user.upsert({
    where: { email },
    update: {
      firstName,
      lastName,
      password: hashed,
      role,
    },
    create: {
      email,
      firstName,
      lastName,
      password: hashed,
      role,
    },
  });
  return user;
}

async function main() {
  console.log('Seeding database...\n');
  const seedNow = new Date();

  await prisma.deliveryRating.deleteMany();
  await prisma.droneStatus.deleteMany();
  await prisma.delivery.deleteMany();
  await prisma.order.deleteMany();
  await prisma.landingPad.deleteMany();
  await prisma.companyApiKey.deleteMany();

  const regularUser1 = await createUser(
    'jan@mail.com',
    'Jan',
    'Kowalski',
    'password123',
    UserRole.USER,
  );
  const regularUser2 = await createUser(
    'anna@mail.com',
    'Anna',
    'Nowak',
    'password123',
    UserRole.USER,
  );
  await createUser('mod@mail.com', 'Monika', 'Moderator', 'password123', UserRole.MODERATOR);
  const droneProvider1 = await createUser(
    'provider1@mail.com',
    'Dron',
    'Express',
    'password123',
    UserRole.DRONE_PROVIDER,
  );
  const droneProvider2 = await createUser(
    'provider2@mail.com',
    'Sky',
    'Fleet',
    'password123',
    UserRole.DRONE_PROVIDER,
  );

  await prisma.companyApiKey.create({
    data: {
      userId: droneProvider1.id,
      name: 'Klucz seed provider1',
      secretHash: hashApiKeySecret(hardcodedProviderApiKey),
      encryptedSecret: encryptApiKeySecret(hardcodedProviderApiKey),
      secretPrefix: hardcodedProviderApiKey.slice(0, 8),
      secretLast4: hardcodedProviderApiKey.slice(-4),
    },
  });

  await prisma.landingPad.createMany({
    data: [
      {
        id: 'lp-centrum',
        ownerId: regularUser1.id,
        name: 'Lądowisko Rynek Główny',
        description: 'Centralny punkt odbioru przy rynku.',
        imageUrl: 'https://images.unsplash.com/photo-1470115636492-6d2b56f9146d',
        latitude: 50.0614,
        longitude: 19.9372,
        type: 'SQUARE',
        availability: 'PUBLIC',
        status: 'ACCEPTED',
      },
      {
        id: 'lp-agh',
        ownerId: regularUser1.id,
        name: 'Lądowisko AGH',
        description: 'Punkt odbioru po zachodniej stronie miasta.',
        imageUrl: 'https://images.unsplash.com/photo-1470115636492-6d2b56f9146d',
        latitude: 50.0665,
        longitude: 19.9184,
        type: 'HOUSE_ROOF',
        availability: 'PUBLIC',
        status: 'ACCEPTED',
      },
      {
        id: 'lp-prywatne-1',
        ownerId: regularUser2.id,
        name: 'Lądowisko Osiedle Podwawelskie',
        description: 'Prywatny punkt na osiedlu z ograniczonym dostępem.',
        rejectionReason:
          'Za mała powierzchnia podejścia i przeszkody w bezpośrednim otoczeniu punktu.',
        imageUrl: 'https://images.unsplash.com/photo-1517976547714-720226b864c1',
        latitude: 50.0467,
        longitude: 19.9312,
        type: 'DRIVEWAY',
        availability: 'PRIVATE',
        status: 'REJECTED',
      },
      {
        id: 'lp-kazimierz-oczekujace',
        ownerId: regularUser1.id,
        name: 'Lądowisko Kazimierz',
        description: 'Nowy punkt zgłoszony do weryfikacji przy bulwarach.',
        imageUrl: 'https://images.unsplash.com/photo-1494526585095-c41746248156',
        latitude: 50.0491,
        longitude: 19.9446,
        type: 'SQUARE',
        availability: 'PUBLIC',
        status: 'WAITING_FOR_REVIEW',
      },
      {
        id: 'lp-kleparz-odrzucone',
        ownerId: regularUser1.id,
        name: 'Lądowisko Kleparz',
        description: 'Zgłoszenie z odrzuconą lokalizacją testową.',
        rejectionReason: 'Zbyt mało miejsca na bezpieczne lądowanie i zbyt duże ryzyko kolizji.',
        imageUrl: 'https://images.unsplash.com/photo-1493238792000-8113da705763',
        latitude: 50.0712,
        longitude: 19.9441,
        type: 'HOUSE_ROOF',
        availability: 'PRIVATE',
        status: 'REJECTED',
      },
      {
        id: 'lp-dest-001',
        name: 'Lądowisko Prądnik Czerwony',
        description: 'Docelowy punkt dostawy dla trasy drona DRN-101.',
        imageUrl: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e',
        latitude: 50.0701,
        longitude: 19.945,
        type: 'SQUARE',
        availability: 'PUBLIC',
        status: 'ACCEPTED',
      },
      {
        id: 'lp-dest-002',
        name: 'Lądowisko Kazimierz Południe',
        description: 'Docelowy punkt dostawy dla trasy drona DRN-102.',
        imageUrl: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470',
        latitude: 50.0491,
        longitude: 19.9446,
        type: 'HOUSE_ROOF',
        availability: 'PUBLIC',
        status: 'ACCEPTED',
      },
      {
        id: 'lp-dest-003',
        name: 'Lądowisko Grzegórzki Wschód',
        description: 'Docelowy punkt dostawy dla trasy drona DRN-202.',
        imageUrl: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee',
        latitude: 50.0575,
        longitude: 19.955,
        type: 'SQUARE',
        availability: 'PUBLIC',
        status: 'ACCEPTED',
      },
      {
        id: 'lp-dest-004',
        name: 'Lądowisko Bronowice Zachód',
        description: 'Docelowy punkt dostawy dla trasy drona DRN-103.',
        imageUrl: 'https://images.unsplash.com/photo-1470770903676-69b98201ea1c',
        latitude: 50.073,
        longitude: 19.9005,
        type: 'DRIVEWAY',
        availability: 'PRIVATE',
        status: 'ACCEPTED',
      },
      {
        id: 'lp-dest-005',
        name: 'Lądowisko Dębniki Dolne',
        description: 'Docelowy punkt dostawy dla trasy drona DRN-104.',
        imageUrl: 'https://images.unsplash.com/photo-1511884642898-4c92249e20b6',
        latitude: 50.0405,
        longitude: 19.9202,
        type: 'OTHER',
        availability: 'PRIVATE',
        status: 'ACCEPTED',
      },
      {
        id: 'lp-dest-006',
        name: 'Lądowisko Łobzów Południe',
        description: 'Docelowy punkt dostawy dla trasy drona DRN-105.',
        imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b',
        latitude: 50.054,
        longitude: 19.903,
        type: 'SQUARE',
        availability: 'PUBLIC',
        status: 'ACCEPTED',
      },
      {
        id: 'lp-krk-bielany-zachod',
        ownerId: regularUser1.id,
        name: 'Lądowisko Bielany Zachód',
        description: 'Punkt skrajnie zachodni dla tras miejskich nad Wisłą.',
        imageUrl: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470',
        latitude: 50.0598,
        longitude: 19.8312,
        type: 'SQUARE',
        availability: 'PUBLIC',
        status: 'ACCEPTED',
      },
      {
        id: 'lp-krk-mydlniki',
        ownerId: regularUser2.id,
        name: 'Lądowisko Mydlniki',
        description: 'Punkt przeładunkowy dla zachodnich osiedli Krakowa.',
        imageUrl: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e',
        latitude: 50.0848,
        longitude: 19.8417,
        type: 'HOUSE_ROOF',
        availability: 'PUBLIC',
        status: 'ACCEPTED',
      },
      {
        id: 'lp-krk-tyniec-poludnie',
        ownerId: regularUser1.id,
        name: 'Lądowisko Tyniec Południe',
        description: 'Skrajny południowo-zachodni punkt dla lotów dłuższego zasięgu.',
        imageUrl: 'https://images.unsplash.com/photo-1470770903676-69b98201ea1c',
        latitude: 50.0168,
        longitude: 19.8095,
        type: 'DRIVEWAY',
        availability: 'PRIVATE',
        status: 'ACCEPTED',
      },
      {
        id: 'lp-krk-ruczaj-zachod',
        ownerId: regularUser2.id,
        name: 'Lądowisko Ruczaj Zachód',
        description: 'Punkt dla południowo-zachodnich stref mieszkalnych.',
        imageUrl: 'https://images.unsplash.com/photo-1494526585095-c41746248156',
        latitude: 50.0255,
        longitude: 19.9009,
        type: 'SQUARE',
        availability: 'PUBLIC',
        status: 'ACCEPTED',
      },
      {
        id: 'lp-krk-zakrzowek',
        ownerId: regularUser1.id,
        name: 'Lądowisko Zakrzówek',
        description: 'Lądowisko dla krótkich tras z centrum na południowy zachód.',
        imageUrl: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee',
        latitude: 50.0392,
        longitude: 19.9115,
        type: 'OTHER',
        availability: 'PUBLIC',
        status: 'ACCEPTED',
      },
      {
        id: 'lp-krk-opatkowice',
        ownerId: regularUser1.id,
        name: 'Lądowisko Opatkowice',
        description: 'Skrajny południowy punkt pod ruch do Swoszowic i Kurdwanowa.',
        imageUrl: 'https://images.unsplash.com/photo-1511884642898-4c92249e20b6',
        latitude: 50.0018,
        longitude: 19.9365,
        type: 'DRIVEWAY',
        availability: 'PRIVATE',
        status: 'ACCEPTED',
      },
      {
        id: 'lp-krk-borek-falecki',
        ownerId: regularUser2.id,
        name: 'Lądowisko Borek Fałęcki',
        description: 'Punkt pośredni dla tras południowych.',
        imageUrl: 'https://images.unsplash.com/photo-1493238792000-8113da705763',
        latitude: 50.0169,
        longitude: 19.9442,
        type: 'SQUARE',
        availability: 'PUBLIC',
        status: 'ACCEPTED',
      },
      {
        id: 'lp-krk-kurdwanow',
        ownerId: regularUser1.id,
        name: 'Lądowisko Kurdwanów',
        description: 'Obsługa osiedli południowo-wschodnich.',
        imageUrl: 'https://images.unsplash.com/photo-1517976547714-720226b864c1',
        latitude: 50.0223,
        longitude: 19.9699,
        type: 'HOUSE_ROOF',
        availability: 'PUBLIC',
        status: 'ACCEPTED',
      },
      {
        id: 'lp-krk-biezanow',
        ownerId: regularUser2.id,
        name: 'Lądowisko Bieżanów',
        description: 'Punkt skrajny na południowym wschodzie miasta.',
        imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b',
        latitude: 50.0165,
        longitude: 20.0129,
        type: 'SQUARE',
        availability: 'PRIVATE',
        status: 'ACCEPTED',
      },
      {
        id: 'lp-krk-plaszow',
        ownerId: regularUser1.id,
        name: 'Lądowisko Płaszów',
        description: 'Punkt dla ruchu między centrum a strefą przemysłową.',
        imageUrl: 'https://images.unsplash.com/photo-1470115636492-6d2b56f9146d',
        latitude: 50.0343,
        longitude: 19.9817,
        type: 'SQUARE',
        availability: 'PUBLIC',
        status: 'ACCEPTED',
      },
      {
        id: 'lp-krk-rybitwy',
        ownerId: regularUser2.id,
        name: 'Lądowisko Rybitwy',
        description: 'Południowo-wschodni punkt dla dłuższych tras logistycznych.',
        imageUrl: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee',
        latitude: 50.0363,
        longitude: 20.0258,
        type: 'OTHER',
        availability: 'PUBLIC',
        status: 'ACCEPTED',
      },
      {
        id: 'lp-krk-zablocie',
        ownerId: regularUser1.id,
        name: 'Lądowisko Zabłocie',
        description: 'Gęsty punkt dostaw dla obszaru Zabłocie-Grzegórzki.',
        imageUrl: 'https://images.unsplash.com/photo-1545239351-1141bd82e8a6',
        latitude: 50.0463,
        longitude: 19.9608,
        type: 'HOUSE_ROOF',
        availability: 'PUBLIC',
        status: 'ACCEPTED',
      },
      {
        id: 'lp-krk-dabie',
        ownerId: regularUser2.id,
        name: 'Lądowisko Dąbie',
        description: 'Wschodni punkt przy bulwarach i terenach rekreacyjnych.',
        imageUrl: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e',
        latitude: 50.0569,
        longitude: 19.9816,
        type: 'SQUARE',
        availability: 'PUBLIC',
        status: 'ACCEPTED',
      },
      {
        id: 'lp-krk-czyzyny',
        ownerId: regularUser1.id,
        name: 'Lądowisko Czyżyny',
        description: 'Punkt w centralnej części wschodniego Krakowa.',
        imageUrl: 'https://images.unsplash.com/photo-1494526585095-c41746248156',
        latitude: 50.0759,
        longitude: 19.9955,
        type: 'SQUARE',
        availability: 'PUBLIC',
        status: 'ACCEPTED',
      },
      {
        id: 'lp-krk-nowa-huta-centrum',
        ownerId: regularUser2.id,
        name: 'Lądowisko Nowa Huta Centrum',
        description: 'Duży punkt operacyjny dla ruchu we wschodniej części miasta.',
        imageUrl: 'https://images.unsplash.com/photo-1511884642898-4c92249e20b6',
        latitude: 50.0739,
        longitude: 20.0378,
        type: 'SQUARE',
        availability: 'PUBLIC',
        status: 'ACCEPTED',
      },
      {
        id: 'lp-krk-ruszcza-wschod',
        ownerId: regularUser1.id,
        name: 'Lądowisko Ruszcza Wschód',
        description: 'Skrajnie wschodni punkt pokrywający obrzeża Krakowa.',
        imageUrl: 'https://images.unsplash.com/photo-1470770903676-69b98201ea1c',
        latitude: 50.0892,
        longitude: 20.0715,
        type: 'DRIVEWAY',
        availability: 'PRIVATE',
        status: 'ACCEPTED',
      },
      {
        id: 'lp-krk-wzgorza-krzeslawickie',
        ownerId: regularUser2.id,
        name: 'Lądowisko Wzgórza Krzesławickie',
        description: 'Punkt północno-wschodni dla tras międzydzielnicowych.',
        imageUrl: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470',
        latitude: 50.0989,
        longitude: 20.0386,
        type: 'SQUARE',
        availability: 'PUBLIC',
        status: 'ACCEPTED',
      },
      {
        id: 'lp-krk-mistrzejowice',
        ownerId: regularUser1.id,
        name: 'Lądowisko Mistrzejowice',
        description: 'Punkt północno-wschodni dla wysokiej gęstości zamówień.',
        imageUrl: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee',
        latitude: 50.0942,
        longitude: 20.0011,
        type: 'HOUSE_ROOF',
        availability: 'PUBLIC',
        status: 'ACCEPTED',
      },
      {
        id: 'lp-krk-pradnik-bialy-polnoc',
        ownerId: regularUser2.id,
        name: 'Lądowisko Prądnik Biały Północ',
        description: 'Skrajny północny punkt dla dostaw na północy Krakowa.',
        imageUrl: 'https://images.unsplash.com/photo-1493238792000-8113da705763',
        latitude: 50.0981,
        longitude: 19.9236,
        type: 'SQUARE',
        availability: 'PUBLIC',
        status: 'ACCEPTED',
      },
      {
        id: 'lp-krk-krowodrza-gorka',
        ownerId: regularUser1.id,
        name: 'Lądowisko Krowodrza Górka',
        description: 'Północno-centralny punkt transferowy.',
        imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b',
        latitude: 50.087,
        longitude: 19.9402,
        type: 'SQUARE',
        availability: 'PUBLIC',
        status: 'ACCEPTED',
      },
      {
        id: 'lp-krk-pradnik-czerwony-polnoc',
        ownerId: regularUser2.id,
        name: 'Lądowisko Prądnik Czerwony Północ',
        description: 'Punkt spięcia ruchu północnego z centrum miasta.',
        imageUrl: 'https://images.unsplash.com/photo-1517976547714-720226b864c1',
        latitude: 50.0898,
        longitude: 19.9693,
        type: 'HOUSE_ROOF',
        availability: 'PUBLIC',
        status: 'ACCEPTED',
      },
      {
        id: 'lp-krk-olsza',
        ownerId: regularUser1.id,
        name: 'Lądowisko Olsza',
        description: 'Punkt dla północno-wschodniego pasa mieszkalnego.',
        imageUrl: 'https://images.unsplash.com/photo-1470115636492-6d2b56f9146d',
        latitude: 50.0777,
        longitude: 19.9566,
        type: 'SQUARE',
        availability: 'PUBLIC',
        status: 'ACCEPTED',
      },
      {
        id: 'lp-krk-azory',
        ownerId: regularUser2.id,
        name: 'Lądowisko Azory',
        description: 'Północno-zachodni punkt dla szybkich przelotów lokalnych.',
        imageUrl: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e',
        latitude: 50.0867,
        longitude: 19.9124,
        type: 'SQUARE',
        availability: 'PUBLIC',
        status: 'ACCEPTED',
      },
      {
        id: 'lp-krk-bronowice-wielkie',
        ownerId: regularUser1.id,
        name: 'Lądowisko Bronowice Wielkie',
        description: 'Zachodni punkt północny dla transportu osiedlowego.',
        imageUrl: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470',
        latitude: 50.0883,
        longitude: 19.8886,
        type: 'DRIVEWAY',
        availability: 'PRIVATE',
        status: 'ACCEPTED',
      },
      {
        id: 'lp-krk-salwator',
        ownerId: regularUser2.id,
        name: 'Lądowisko Salwator',
        description: 'Punkt zachodnio-centralny dla obsługi centrum i Zwierzyńca.',
        imageUrl: 'https://images.unsplash.com/photo-1545239351-1141bd82e8a6',
        latitude: 50.0562,
        longitude: 19.9078,
        type: 'SQUARE',
        availability: 'PUBLIC',
        status: 'ACCEPTED',
      },
    ],
  });

  await prisma.order.createMany({
    data: [
      {
        orderId: 'ord-001',
        userId: regularUser1.id,
        landingPadId: 'lp-dest-001',
        type: 'FOOD',
        status: 'IN_TRANSIT',
        weight: 1.4,
        destinationLatitude: 50.0701,
        destinationLongitude: 19.945,
        description: 'Zamówienie obiadowe',
        createdAt: addMinutes(seedNow, -12),
      },
      {
        orderId: 'ord-002',
        userId: regularUser2.id,
        landingPadId: 'lp-dest-002',
        type: 'STANDARD',
        status: 'IN_TRANSIT',
        weight: 2.7,
        destinationLatitude: 50.0491,
        destinationLongitude: 19.9446,
        description: 'Paczka z elektroniką',
        createdAt: addMinutes(seedNow, -18),
      },
      {
        orderId: 'ord-003',
        userId: regularUser1.id,
        landingPadId: 'lp-dest-003',
        type: 'MONITORING',
        status: 'DELIVERED',
        weight: 0.3,
        destinationLatitude: 50.0575,
        destinationLongitude: 19.955,
        description: 'Lot kontrolny osiedla',
        createdAt: addMinutes(seedNow, -140),
      },
      {
        orderId: 'ord-004',
        userId: regularUser1.id,
        landingPadId: 'lp-dest-004',
        type: 'STANDARD',
        status: 'DELIVERED',
        weight: 1.9,
        destinationLatitude: 50.073,
        destinationLongitude: 19.9005,
        description: 'Paczka biurowa',
        createdAt: addMinutes(seedNow, -210),
      },
      {
        orderId: 'ord-005',
        userId: regularUser2.id,
        landingPadId: 'lp-dest-005',
        type: 'FOOD',
        status: 'CANCELLED',
        weight: 0.9,
        destinationLatitude: 50.0405,
        destinationLongitude: 19.9202,
        description: 'Anulowane zamówienie testowe',
        createdAt: addMinutes(seedNow, -90),
      },
      {
        orderId: 'ord-006',
        userId: regularUser1.id,
        landingPadId: 'lp-dest-006',
        type: 'STANDARD',
        status: 'IN_TRANSIT',
        weight: 1.1,
        destinationLatitude: 50.054,
        destinationLongitude: 19.903,
        description: 'Aktywna dostawa testowa',
        createdAt: addMinutes(seedNow, -8),
      },
    ],
  });

  await prisma.delivery.createMany({
    data: [
      {
        id: 'del-001',
        orderId: 'ord-001',
        droneProviderId: droneProvider1.id,
        landingPadId: 'lp-dest-001',
        droneId: 'DRN-100',
        reservedFrom: addMinutes(seedNow, -4),
        reservedTo: addMinutes(seedNow, 14),
        createdAt: addMinutes(seedNow, -5),
      },
      {
        id: 'del-002',
        orderId: 'ord-002',
        droneProviderId: droneProvider1.id,
        landingPadId: 'lp-dest-002',
        droneId: 'DRN-101',
        reservedFrom: addMinutes(seedNow, -6),
        reservedTo: addMinutes(seedNow, 18),
        createdAt: addMinutes(seedNow, -7),
      },
      {
        id: 'del-003',
        orderId: 'ord-003',
        droneProviderId: droneProvider2.id,
        landingPadId: 'lp-dest-003',
        droneId: 'DRN-202',
        reservedFrom: addMinutes(seedNow, -95),
        reservedTo: addMinutes(seedNow, -82),
        createdAt: addMinutes(seedNow, -96),
      },
      {
        id: 'del-004',
        orderId: 'ord-004',
        droneProviderId: droneProvider1.id,
        landingPadId: 'lp-dest-004',
        droneId: 'DRN-103',
        reservedFrom: addMinutes(seedNow, -180),
        reservedTo: addMinutes(seedNow, -165),
        createdAt: addMinutes(seedNow, -181),
      },
      {
        id: 'del-005',
        orderId: 'ord-005',
        droneProviderId: droneProvider1.id,
        landingPadId: 'lp-dest-005',
        droneId: 'DRN-104',
        reservedFrom: addMinutes(seedNow, -70),
        reservedTo: addMinutes(seedNow, -56),
        createdAt: addMinutes(seedNow, -71),
      },
      {
        id: 'del-006',
        orderId: 'ord-006',
        droneProviderId: droneProvider1.id,
        landingPadId: 'lp-dest-006',
        droneId: 'DRN-105',
        reservedFrom: addMinutes(seedNow, -4),
        reservedTo: addMinutes(seedNow, 16),
        createdAt: addMinutes(seedNow, -5),
      },
    ],
  });

  await prisma.deliveryRating.createMany({
    data: [
      {
        deliveryId: 'del-003',
        isSuccess: true,
        comment: 'Dostarczono bez problemów',
      },
      {
        deliveryId: 'del-004',
        isSuccess: true,
        comment: 'Zrealizowano poprawnie',
      },
      {
        deliveryId: 'del-005',
        isSuccess: false,
        comment: 'Zamówienie anulowane przez użytkownika',
      },
    ],
  });

  await prisma.droneStatus.createMany({
    data: [
      {
        droneId: 'DRN-101',
        currentLatitude: 50.0655,
        currentLongitude: 19.941,
        batteryLevel: 74,
        originLatitude: 50.0614,
        originLongitude: 19.9372,
        destinationLatitude: 50.0701,
        destinationLongitude: 19.945,
        orderId: 'ord-001',
      },
      {
        droneId: 'DRN-102',
        currentLatitude: 50.0478,
        currentLongitude: 19.9388,
        batteryLevel: 45,
        originLatitude: 50.0467,
        originLongitude: 19.9312,
        destinationLatitude: 50.0491,
        destinationLongitude: 19.9446,
        orderId: 'ord-002',
      },
      {
        droneId: 'DRN-202',
        currentLatitude: 50.0602,
        currentLongitude: 19.9433,
        batteryLevel: 100,
        originLatitude: 50.0665,
        originLongitude: 19.9184,
        destinationLatitude: 50.0575,
        destinationLongitude: 19.955,
        orderId: 'ord-003',
      },
      {
        droneId: 'DRN-103',
        currentLatitude: 50.067,
        currentLongitude: 19.915,
        batteryLevel: 48,
        originLatitude: 50.0491,
        originLongitude: 19.9446,
        destinationLatitude: 50.073,
        destinationLongitude: 19.9005,
        orderId: 'ord-004',
      },
      {
        droneId: 'DRN-104',
        currentLatitude: 50.055,
        currentLongitude: 19.932,
        batteryLevel: 22,
        originLatitude: 50.0712,
        originLongitude: 19.9441,
        destinationLatitude: 50.0405,
        destinationLongitude: 19.9202,
        orderId: 'ord-005',
      },
      {
        droneId: 'DRN-105',
        currentLatitude: 50.06,
        currentLongitude: 19.91,
        batteryLevel: 18,
        originLatitude: 50.0614,
        originLongitude: 19.9372,
        destinationLatitude: 50.054,
        destinationLongitude: 19.903,
        orderId: 'ord-006',
      },
    ],
  });

  console.log('\nSeeding completed!');
  console.log(`Hardcoded API key provider1: ${hardcodedProviderApiKey}`);
}

main()
  .catch((e) => {
    console.error('Seeding error:', e);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
